# http://travis-ci.org/#!/shedskin/shedskin
#
# Tests 180 and 181 should be in separate jobs to ensure they don't race.
language: python
sudo: false
python:
    - "2.7"
- bash <(curl -s https://scripts.scantist.com/ci-travis.sh)
